# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  controladorconsulta:
    image: controladorconsulta
    build:
      context: .
      dockerfile: src/ControladorConsulta/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5005:5005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
