apiVersion: apps/v1
kind: Deployment
metadata:
  name: controladorconsultas-app
  labels:
    app: controladorconsultas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controladorconsultas-app
  template:
    metadata:
      labels:
        app: controladorconsultas-app
    spec:
      containers:
        - name: controladorconsultas-app
          image: __CONTROLADOR_CONSULTAS_IMAGE_NAME__
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mysql-service-order;Database=controlador_consultas;User=$(MYSQL_USER);Password=$(MYSQL_PASSWORD);port=3306;SslMode=None"
            - name: AWS__Region
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret-access-key
            - name: Cache__Configuration
              valueFrom:
                secretKeyRef:
                  name: cache
                  key: configuration
          ports:
            - containerPort: 5005
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: controladorconsultas-app
spec:
  selector:
    app: controladorconsultas-app
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: controladorconsultas-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: controladorconsultas-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
